# Localized data for pt-PT

ConvertFrom-StringData @'
###PSLOC
CompareOpProgressCompleted=A comparação hash do ficheiro foi concluída!
CompareOpProgressMessage=A comparar o hash do ficheiro, origem: {0}
CompareOpProgressStatus=Em execução...
EmailNotificationSentWithSuccess=Notificação de email enviada com sucesso
ErrorBasePathNotFound=Não foi possível encontrar o caminho base '{0}' porque o mesmo não existe.
ErrorInvalidArgument=O valor do parametro '{0}' não é válido
ErrorInvalidSetting=O valor da opção '{0}' não é válido
ErrorLoadingScript=There was an error loading '{0}': {1}
ErrorPathNotFound=Não foi possível encontrar o caminho '{0}' porque o mesmo não existe.
ErrorPSVersionFunctionNotSupported=A função '{0}' não é suportada pela sua versão de Powershell. Esta operação requer no mínimo a versão '{1}'
ErrorSettingsFileNotFound=O ficheiro de configuração '{0}' ainda não foi criado
ErrorUtilityParameterRequired=Para utilizar '{0}', o parâmetro '{1}' deverá ser definido corretamente
ErrorUtilityParameterRequiredMode=Para utilizar o modo '{0}', o parâmetro '{1}' deverá ser definido corretamente
ErrorUtilityPathNotFound=O modo '{0}' foi selecionado, mas o caminho '{1}' não existe!
ErrorUtilityPathNotValidFile=O modo '{0}' foi selecionado, mas o caminho '{1}' não é um ficheiro válido!
ErrorUtilitySettingsFileDoesNotExists=Para utilizar '{0}', o ficheiro de configuração deverá ser criado antes. Para criar o ficheiro, por favor, utiliza o modo '{1}'
ErrorUtilitySettingsFileDoesNotExistsMode=O modo '{0}' foi selecionado, mas o ficheiro de configuração ainda não foi criado. Para criar o ficheiro, por favor, utiliza o modo '{1}'
ErrorUtilityValidateFileNotFound=O ficheiro não existe neste endereço: {0}
DiscoveringFilesProgressCompleted=A descoberta de ficheiros foi concluída!
DiscoveringFilesProgressMessage=A descobrir ficheiros, a partir de '{0}'
DiscoveringFilesProgressStatus=Em execução...
GenerateOpProgressMessage=A gerar o checksum, origem: '{0}'
GenerateOpCounterProgressStatus=Ficheiro {0} de {1}
GenerateOpProgressStatus=Em execução...
GenerateOpProgressCompleted=A geração de checksum foi concluída!
OpCompleted=Operação concluída!
PrintChecksumProgressCompleted=A impressão dos checksums foi concluída!
PrintChecksumProgressMessage=A imprimir os checksums
PrintChecksumProgressStatus=Em execução...
RemoveSettingSuccess=[ Removed ] O parâmetro '{0}' foi removido com sucesso
ReportSummaryAgent=Agente: {0}
ReportSummaryAuthor=Autor: {0}
ReportSummaryChecksumAlgorithm=Algoritimo checksum: {0}
ReportSummaryChecksumFilePath=Caminho do ficheiro checksum: {0}
ReportSummaryDescription=Descrição: {0}
ReportSummaryEndedAt=Terminou em: {0}
ReportSummaryFilePath=Caminho do ficheiro: {0}
ReportSummaryOperationMode=Tipo de operação: {0}
ReportSummaryOutputFilePath=Caminho do ficheiro de relatório: {0}
ReportSummaryPath=Caminho: {0}
ReportSummaryProjectUrl=Url do Projeto: {0}
ReportSummaryStartedAt=Começou at: {0}
ReportSummaryTotalFailed=Total de falhas: {0}
ReportSummaryTotalFileNotFound=Total de ficheiros não encontrados: {0}
ReportSummaryTotalGenerated=Total gerados: {0}
ReportSummaryTotalOfItems=Total of itens: {0}
ReportSummaryTotalPassed=Total de sucessos: {0}
ReportSummaryVersion=Versão: {0}
ShowMailerSettingEncryption=Encriptação: {0}
ShowMailerSettingFilePath=Caminho do ficheiro: {0}
ShowMailerSettingPassword=Palavra-passe: {0}
ShowMailerSettingPort=Porta: {0}
ShowMailerSettingSmtpServer=Servidor SMTP: {0}
ShowMailerSettingUsername=Nome de utilizador: {0}
SetSettingSuccess=[ Definido ] O parâmetro '{0}' foi definido com sucesso
ValidateOpProgressMessage=A validar o ficheiro checksum, origem: '{0}'
ValidateOpProgressStatus=Em execução {0}
ValidateOpProgressCompleted=A validação do ficheiro checksum foi concluída!
ValidationEmailNotificationGreetings=Olá,
ValidationEmailNotificationInstructions=Por favor, segue o resultado da validação:
ValidationEmailNotificationMoreInfo=Para mais informações consulte o relatório em anexo.
ValidationEmailNotificationSignature={0}
ValidationEmailNotificationSubject={0} - resultado da validação
ValidationEmailNotificationTotalFileNotFound= - Total de ficheiros não encontrados: {0}
ValidationEmailNotificationTotalFailed= - Total de falhas: {0}
ValidationEmailNotificationTotalItems= - Total de itens: {0}
ValidationEmailNotificationTotalPassed= - Total de sucessos: {0}
ValidationFailed=[ Falhou ] {0} (Hash: {1}, Esperado: {2})
ValidationPassed=[ Passou ] {0}
VerboseLoadingScript=A carregar o ficheiro '{0}'.
VerboseMoreInfo=Para mais informações utiliza a flag -Verbose
###PSLOC
'@